package example:host;

interface game-api {
  record color {
    r: f32,
    g: f32,
    b: f32,
    a: f32
  }

  record position {
    x: f32,
    y: f32
  }

  record text-command {
    text: string,
    position: position,
    size: f32,
    color: color
  }

  variant render-command {
    text(text-command)  
  }

  resource game-instance {
    constructor();

    run-frame: func() -> list<render-command>;
  }
}

world hotreload-example {
  export game-api;
}